speaches-ai/speaches

Taskfile.yaml
compose.yaml
flake.nix
poetry.lock
pyproject.toml
tests/app_test.py

- **chore: add more tasks**
- **refactor: simplify tests**
- **deps: remove unused dev packages**
- **deps: remove unused client packages**
- **deps: regen poetry.lock**
- **feat: docker multi-arch builds**

minor test refactor

---

poetry.lock
pyproject.toml
speaches/asr.py
speaches/main.py
speaches/server_models.py
speaches/utils.py

- **feat: further improve openai compatabilit + refactor**
- **chore: log file transcription time**
- **feat: add translation endpoint**
- **feat: add streaming responses**
- **deps: add youtube-dl as dev dependency**

translation streaming and more

---

faster_whisper_server/config.py
faster_whisper_server/gradio_app.py
faster_whisper_server/main.py
poetry.lock
pyproject.toml
tests/api_model_test.py
tests/app_test.py
tests/conftest.py
tests/sse_test.py

- **deps: add gradio**
- **feat: add a playground**
- **misc: tests**

gradio playground

---

faster_whisper_server/main.py

feat: support hotwords

---

README.md

Please let me know if you rather have me copy paste some of the content to this repo. Happy to do that too. Submitting this PR to start the discussion.

add tutorial for kubernetes

---

.github/workflows/test.yaml

This reverts commit 3df8751c2a42ad77c86bc924905988fe54c31adf.

Revert "wip"

---

compose.yaml
pyproject.toml
src/faster_whisper_server/gradio_app.py
src/faster_whisper_server/logger.py
uv.lock

- **chore: disable gradio telemetry**
- **chore: set root logger level to info**
- **chore: format compose**
- **fix: gradio pydantic error**

misc changes

---

src/faster_whisper_server/config.py

I took me some time to figure it out so I suggest adding this example :)

docs: mention quantization example for env variable

---

src/faster_whisper_server/config.py
src/faster_whisper_server/dependencies.py
src/faster_whisper_server/main.py

feat: token based auth

---

pyproject.toml
src/faster_whisper_server/asr.py
src/faster_whisper_server/config.py
src/faster_whisper_server/routers/stt.py
uv.lock

- **feat: return 4xx on invalid files (#164)**
- **feat: support BatchedInferencePipeline (#169)**

address issues

---

.pre-commit-config.yaml
Dockerfile
src/faster_whisper_server/logger.py

- **add `detect-secrets` pre-commit hook**
- **use dict to configure the logger (also fixes #114)**
- **don't install opentelemetry deps in docker image**
- **fix: docker image not running in offline mode (#127)**

misc fixes

---

Dockerfile
compose.yaml

healtcheck on compose 

---

src/speaches/gradio_app.py

Problem is described in https://github.com/speaches-ai/speaches/issues/249 .
Additional Testing
* Building and running the gradio app in a k8s environment
Sorry for the incomplete PR earlier!  This should finalize the fixes.

Finish ADDING LOOPBACK_HOST_URL Environment Variable

---

flake.nix

fix: no cuda for macos

---

.github/workflows/docker-build-and-push.yaml
Dockerfile
compose.cuda.yaml
pyproject.toml
uv.lock

feat: add cuda 12.4.1 support

---

flake.lock
flake.nix
pyproject.toml
src/speaches/hf_utils.py
uv.lock

- **deps: add nixpkgs-master flake input**
- **chore: pin kokoro revision when testing**
- **deps: update opentelemetry dependencies**
- **deps: add opentelemetry-instrumentation-openai-v2**
- **deps: add opentelemetry-instrumentation-asgi**
- **deps: add opentelemetry-instrumentation-openai**
- **deps: add docker and docker-compose to flake.nix**

misc deps changes

---

docs/CNAME

https://www.mkdocs.org/user-guide/deploying-your-docs/#custom-domains

docs: add CNAME (fixes #303)

---

Dockerfile
Taskfile.yaml
compose.cpu.yaml
compose.cuda.yaml
examples/youtube/script.sh
src/speaches/config.py
src/speaches/realtime/session.py
src/speaches/routers/stt.py
src/speaches/ui/tabs/stt.py
tests/conftest.py
tests/model_manager_test.py
tests/sse_test.py

- **config: remove `whisper.model` option (#312 and #313)**
- **chore: cleanup Taskfile**
- **fix: 'typing.TypeAliasType' object is not iterable**

remove config options

---

.gitignore
pyproject.toml
src/speaches/executors/kokoro/model_manager.py
src/speaches/executors/piper/model_manager.py
src/speaches/main.py
src/speaches/routers/chat.py
src/speaches/ui/tabs/audio_chat.py
src/speaches/ui/tabs/stt.py
src/speaches/utils.py

This PR updates dependency versions and adds in missing error handling, including a large macos speedup on apple silicon because it is now supported in onnxruntime.
1. **Refactored error handling for clearer and more actionable feedback**
- Added `APIProxyError` and error formatting utility function to provide clearer more actionable errors.
- Updated all dependent code to use the new error handling pattern.
- Improved error handling and user feedback in UI and backend, including early validation of audio file presence.
- Enhanced traceability via unique error IDs and ISO 8601 UTC timestamps in all errors.
3. **MacOS and Apple Silicon major speedup and dependency version updates**
- Upgraded `onnxruntime` to 1.22.0 for a major Apple Silicon inference speedup.
- Added info-level logging …

Major Apple Silicon ONNX speedup, actionable error handling and guidance

---

README.md
docs/index.md
src/speaches/config.py
src/speaches/dependencies.py
src/speaches/executors/kokoro/model_manager.py
src/speaches/executors/kokoro/utils.py
src/speaches/executors/piper/model_manager.py
src/speaches/executors/piper/utils.py
src/speaches/routers/models.py

- **feat: add OpenWebUI audio model and voices routes**
- **feat: prioritize `CUDAExecutionProvider` provider when available**
- **docs: fix incorrect URLs**
- **feat: provide a way for configuring ORT providers**

269 write an open webui integration tutorial

---

src/speaches/executors/piper/utils.py

Hey there, I was unable to download and list models from the piper registry recently. Apparently there are some models that do not comply an assertion on the model id which causes the entire application to crash with an `Internal Server Error`. Here's the stacktrace.
```
Traceback (most recent call last): File "/Users/dsegoviat/projects/speaches/.venv/lib/python3.12/site-packages/uvicorn/protocols/http/h11_impl.py", line 404, in run_asgi result = await app( # type: ignore[func-returns-value] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/Users/dsegoviat/projects/speaches/.venv/lib/python3.12/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__ return await self.app(scope, receive, send) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File …
```

fix: skip non-conforming piper models

---

docs/usage/realtime-api.md
src/speaches/dependencies.py
src/speaches/main.py
src/speaches/realtime/session.py
src/speaches/realtime/utils.py
src/speaches/routers/realtime/rtc.py
src/speaches/routers/realtime/ws.py
tests/realtime_api_test.py

Fixes #521
This PR fixes broken WebSocket authentication and implements transcription-only mode for the Realtime API. The authentication was previously broken due to FastAPI dependency injection incompatibility with WebSocket connections.
- **Problem**: FastAPI dependency injection doesn't work with WebSocket authentication
- **Solution**: Implemented manual `verify_websocket_api_key` with proper error handling
- **Impact**: WebSocket connections now work reliably with authentication
- `Authorization: Bearer <token>` header
- `X-API-Key: <token>` header
- `api_key=<token>` query parameter (Speaches extension)
- Added `intent=transcription` parameter to disable response generation
- Added `language` parameter for transcription language specification
- Added `transcription_model` parameter …

Fix WebSocket Authentication and Add Transcription-Only Mode
